//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSYM_SinavTakvimi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Bu uygulama Harun ÇETİN tarafından geliştirilmiştir.
Yazılım geliştirmeye ve elektroniğe dair güncel yazılarımı görmek için web sitemi ziyaret edin. 
Görüş, öneri ve sorularınız için e-posta adresime yazın.

Web: http://www.haruncetin.com.tr
E-Posta: mailto:harun@haruncetin.com.tr
")]
        public string about {
            get {
                return ((string)(this["about"]));
            }
            set {
                this["about"] = value;
            }
        }
    }
}
